# History in cache directory:
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.config/zsh/.zsh_history

# Enable colors and change prompt:
autoload -U colors && colors	# Load colors
PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "
setopt autocd		# Automatically cd into typed directory.
stty stop undef		# Disable ctrl-s to freeze terminal.
setopt interactive_comments




setopt GLOB_DOTS
#share commands between terminal instances or not
unsetopt SHARE_HISTORY
#setopt SHARE_HISTORY

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export HISTCONTROL=ignoreboth:erasedups
export EDITOR='nvim'

#PS1='[\u@\h \W]\$ '

if [ -d "$HOME/.bin" ] ;
  then PATH="$HOME/.bin:$PATH"
fi

if [ -d "$HOME/.local/bin" ] ;
  then PATH="$HOME/.local/bin:$PATH"
fi

#list
alias ls='ls --color=auto'
alias la='ls -a'
alias ll='ls -la'
alias l='ls'
alias l.="ls -A | egrep '^\.'"
alias clean="sudo pacman -Rns $(pacman -Qdtq)"
alias update="sudo pacman -Syu"
alias n="nvim"

## Colorize the grep command output for ease of use (good for log files)##
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

#ps
alias psa="ps auxf"
alias psgrep="ps aux | grep -v grep | grep -i -e VSZ -e"

#add new fonts
alias update-fc='sudo fc-cache -fv'

#switch between bash and zsh
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

# quickly kill polybar
alias kp='killall polybar'

#Recent Installed Packages
alias rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -200 | nl"
alias riplong="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -3000 | nl"

#iso and version used to install ArcoLinux
alias iso="cat /etc/dev-rel | awk -F '=' '/ISO/ {print $2}'"

#get the error messages from journalctl
alias jctl="journalctl -p 3 -xb"

#know what you do in these files
alias Elightdm="sudo $EDITOR /etc/lightdm/lightdm.conf"
alias Epacman="sudo $EDITOR /etc/pacman.conf"
alias grub="sudo $EDITOR /etc/default/grub"
alias Econfgrub="sudo $EDITOR /boot/grub/grub.cfg"
alias Emkinitcpio="sudo $EDITOR /etc/mkinitcpio.conf"
alias Emirrorlist="sudo $EDITOR /etc/pacman.d/mirrorlist"
alias Esddm="sudo $EDITOR /etc/sddm.conf"
alias Esddmk="sudo $EDITOR /etc/sddm.conf.d/kde_settings.conf"
alias Efstab="sudo $EDITOR /etc/fstab"
alias Ensswitch="sudo $EDITOR /etc/nsswitch.conf"
alias Esamba="sudo $EDITOR /etc/samba/smb.conf"
alias Egnupgconf="sudo nano /etc/pacman.d/gnupg/gpg.conf"
alias Ez="$EDITOR ~/.config/zsh/.zshrc"
alias Ebsp="$EDITOR ~/.config/bspwm/bspwmrc"
alias Esx="$EDITOR ~/.config/sxhkd/sxhkdrc"
alias Eplb="$EDITOR ~/.config/polybar/config"


# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


#remove
alias ccgit="rm -r ~/.cache/git"


[[ -f ~/.zshrc-personal ]] && . ~/.zshrc-personal

neofetch

source ~/.config/zsh/plugins/zsh-autosuggestions.zsh
#where to get the file? git clone https://github.com/zdharma-continuum/fast-syntax-highlighting ~/.config/zsh/plugins/fsh
source ~/.config/zsh/plugins/fsh/fast-syntax-highlighting.plugin.zsh 
